import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1764256423524 implements MigrationInterface {
    name = 'Migrations1764256423524'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "car-history" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "plate_number" varchar(255) NOT NULL, "entry_time" datetime NOT NULL, "exit_time" datetime, "entry_image" varchar(255), "exit_image" varchar(255), "entry_location" varchar(255) NOT NULL, "exit_location" varchar(255))`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "car_history_id" varchar, "user_id" varchar, CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "REL_3e4c5ce2fa126d64cf7f7b5dea" UNIQUE ("car_history_id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "username" varchar(255) NOT NULL, "password" varchar(255) NOT NULL, "role" varchar CHECK( "role" IN ('admin','user','guest') ) NOT NULL DEFAULT ('user'), "plate_number" varchar(255), "start_date" datetime, "end_date" datetime, "is_membership_paid" boolean DEFAULT (0), "refresh_token" varchar(500), CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"))`);
        await queryRunner.query(`CREATE TABLE "parking-lot" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "lot_code" varchar(255) NOT NULL, "lot_name" varchar(255) NOT NULL, "is_available" boolean NOT NULL DEFAULT (1), CONSTRAINT "UQ_5c234c723ebb7600fff7678c66b" UNIQUE ("lot_code"))`);
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "car_history_id" varchar, "user_id" varchar, CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "REL_3e4c5ce2fa126d64cf7f7b5dea" UNIQUE ("car_history_id"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_34e537d6261c55286aa58921ada" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "vnp_url", "transaction_no", "bank_code", "description", "is_paid", "bill_type", "car_history_id", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "vnp_url", "transaction_no", "bank_code", "description", "is_paid", "bill_type", "car_history_id", "user_id" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "car_history_id" varchar, "user_id" varchar, CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "REL_3e4c5ce2fa126d64cf7f7b5dea" UNIQUE ("car_history_id"))`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "vnp_url", "transaction_no", "bank_code", "description", "is_paid", "bill_type", "car_history_id", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "vnp_url", "transaction_no", "bank_code", "description", "is_paid", "bill_type", "car_history_id", "user_id" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "parking-lot"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`DROP TABLE "car-history"`);
    }

}
