import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1764143777463 implements MigrationInterface {
    name = 'Migrations1764143777463'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "FK_34e537d6261c55286aa58921ada" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"))`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"))`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_34e537d6261c55286aa58921ada" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"))`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"))`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "FK_34e537d6261c55286aa58921ada" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
    }

}
