import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1764139694697 implements MigrationInterface {
    name = 'Migrations1764139694697'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
        await queryRunner.query(`CREATE TABLE "temporary_user" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "username" varchar(255) NOT NULL, "password" varchar(255) NOT NULL, "role" varchar CHECK( "role" IN ('admin','user') ) NOT NULL DEFAULT ('user'), "refresh_token" varchar(500), "plate_number" varchar(255), "start_date" datetime, "end_date" datetime, "is_membership_paid" boolean DEFAULT (0), CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "temporary_user"("id", "created_at", "updated_at", "deleted_at", "username", "password", "role", "refresh_token") SELECT "id", "created_at", "updated_at", "deleted_at", "username", "password", "role", "refresh_token" FROM "user"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`ALTER TABLE "temporary_user" RENAME TO "user"`);
        await queryRunner.query(`CREATE TABLE "temporary_bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_34e537d6261c55286aa58921ada" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "bill"`);
        await queryRunner.query(`DROP TABLE "bill"`);
        await queryRunner.query(`ALTER TABLE "temporary_bill" RENAME TO "bill"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), "bill_type" varchar CHECK( "bill_type" IN ('temporary','monthly','membership') ) NOT NULL DEFAULT ('temporary'), "user_id" varchar, CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code", "bill_type", "user_id" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
        await queryRunner.query(`ALTER TABLE "user" RENAME TO "temporary_user"`);
        await queryRunner.query(`CREATE TABLE "user" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "username" varchar(255) NOT NULL, "password" varchar(255) NOT NULL, "role" varchar CHECK( "role" IN ('admin','user') ) NOT NULL DEFAULT ('user'), "refresh_token" varchar(500), CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "user"("id", "created_at", "updated_at", "deleted_at", "username", "password", "role", "refresh_token") SELECT "id", "created_at", "updated_at", "deleted_at", "username", "password", "role", "refresh_token" FROM "temporary_user"`);
        await queryRunner.query(`DROP TABLE "temporary_user"`);
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
        await queryRunner.query(`ALTER TABLE "bill" RENAME TO "temporary_bill"`);
        await queryRunner.query(`CREATE TABLE "bill" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime DEFAULT (datetime('now')), "updated_at" datetime DEFAULT (datetime('now')), "deleted_at" datetime, "bill_code" varchar(255) NOT NULL, "bill_time" datetime NOT NULL, "amount" decimal(10,2) NOT NULL, "payment_method" varchar(255) NOT NULL, "description" varchar(255), "is_paid" boolean NOT NULL DEFAULT (0), "qr_code" varchar(255), "car_history_id" varchar NOT NULL, "vnp_url" varchar(255), "transaction_no" varchar(255), "bank_code" varchar(255), CONSTRAINT "UQ_65e080814ef684970ae977cf1b1" UNIQUE ("bill_code"), CONSTRAINT "UQ_8bc949af4d0949696ad4538d833" UNIQUE ("car_history_id"), CONSTRAINT "FK_3e4c5ce2fa126d64cf7f7b5dea0" FOREIGN KEY ("car_history_id") REFERENCES "car-history" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bill"("id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code") SELECT "id", "created_at", "updated_at", "deleted_at", "bill_code", "bill_time", "amount", "payment_method", "description", "is_paid", "car_history_id", "vnp_url", "transaction_no", "bank_code" FROM "temporary_bill"`);
        await queryRunner.query(`DROP TABLE "temporary_bill"`);
    }

}
